version: '3'
services:
  server:
    image:  node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=iykestrike
      - PGHOST=db
      - PGPASSWORD=ballislife
      - PGDATABASE=basketball-db
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=basketball-db
      - POSTGRES_USER=iykestrike
      - POSTGRES_PASSWORD=ballislife
volumes:
  dbdata:
